FMRadio: match playlist by name instead
* Avoids detection failing to find existing playlist and creating new
  one every time you record something, therefore fixes:

java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Music/FM Recordings owner_package_name=com.android.fmradio _display_name=FM Recordings mime_type=audio/mpegurl name=FM Recordings _data=/storage/emulated/0/Music/FM Recordings date_added=1683921081 relative_path=Music/

Change-Id: I92227e154540d072ae26887dc9a137d16009b988