Fix several possible NoSuchMethod errors for API >33
* According to documentation of NotificationChannel class method [setBlockable](https://developer.android.com/reference/android/app/NotificationChannel#setBlockable(boolean)) was added in api 33.
* But in this app's manifest min API is 26, so in api 26 it crash with NoSuchMethodError.

Change-Id: Iebbcfa32090c7e8cfa23f46396f68efbe4f9f256